spring:
  profiles:
    #设置这个属性是为了指导logback的输出环境
    active: dev
#配置文件加密
jasypt:
  encryptor:
    bean: sbrEncryptorBean
security:
  oauth2:
    resource:
      filter-order: 3
#auth.exculsive.urls: /**/api/v*/auth/token
auth.exculsive.urls: /**
---
server:
  port: 20901
spring:
  profiles: dev
  cloud:
    consul:
      host: localhost
      #  Consul监听端口8500
      port: 8500
      enabled: true
      discovery:
        # 配置服务注册到Consul上
        register: true
        # 配置注册到consul 服务的id
        instance-id: ${spring.application.name}:${server.port}
        service-name: ${spring.application.name}
        # 很重到如果没有这个服务在Consul是注册失败的导致服务不能被调用，解决Consul页面服务检查失败报错问题
        heartbeat:
          enabled: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sp-assets?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initial-size: 5
    min-idle: 5
    max-idle: 100
    max-wait: 10000
    validation-query: SELECT 1
    #没次使用连接时进行校验，会影响系统性能。默认为false
    test-on-borrow: true
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    # 需要同步到的数据源
    secondary:
      url: jdbc:mysql://192.168.7.114:16120/cybersky?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: cybersky
      password: Cyber.sky@305
      driver-class-name: com.mysql.jdbc.Driver
      #type: com.zaxxer.hikari.HikariDataSource
      initial-size: 5
      min-idle: 5
      max-idle: 100
      max-wait: 10000
      validation-query: SELECT 1
    #没次使用连接时进行校验，会影响系统性能。默认为false
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
security:
  oauth2:
    resource:
      id: sp-assets
      user-info-uri: http://localhost:9002/oauth/user
      prefer-token-info: false
---

server:
  port: 20901 #启动端口
spring:
  profiles: prod
  cloud:
    consul:
      host: product-consul
      #  Consul监听端口8500
      port: 8500
      enabled: true
      discovery:
        # 配置服务注册到Consul上
        register: true
        # 配置注册到consul 服务的id
        instance-id: ${spring.application.name}:${server.port}
        service-name: ${spring.application.name}
        # 很重到如果没有这个服务在Consul是注册失败的导致服务不能被调用，解决Consul页面服务检查失败报错问题
        heartbeat:
          enabled: true
#  datasource:
#    url: jdbc:mysql://product-mysql:3306/sp-assets?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: Admin@123
  datasource:
    url: jdbc:mysql://product-mysql:3306/sp-assets?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#    url: jdbc:mysql://192.168.7.151:3706/sp-assets?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Admin@123
    initial-size: 5
    min-idle: 5
    max-idle: 100
    max-wait: 10000
    validation-query: SELECT 1
    #没次使用连接时进行校验，会影响系统性能。默认为false
    test-on-borrow: true
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    # 需要同步到的数据源
    secondary:
      url: jdbc:mysql://192.168.7.114:16120/cybersky?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: cybersky
      password: Cyber.sky@305
      driver-class-name: com.mysql.jdbc.Driver
      #type: com.zaxxer.hikari.HikariDataSource
      initial-size: 5
      min-idle: 5
      max-idle: 100
      max-wait: 10000
      validation-query: SELECT 1
      #没次使用连接时进行校验，会影响系统性能。默认为false
      test-on-borrow: true
      test-while-idle: true

      time-between-eviction-runs-millis: 60000
    jpa:
      hibernate:
        ddl-auto: none
      database-platform: org.hibernate.dialect.MySQL5Dialect
      show-sql: false
security:
  oauth2:
    resource:
      id: sp-assets
      user-info-uri: http://prometheus-uia:9002/oauth/user
      prefer-token-info: false
auth.exculsive.urls: /**
